In [1]:
# np day 1
import numpy as np


In [4]:
a = np.array([1,2,3,4,5,6,6,7])

In [5]:
a

array([1, 2, 3, 4, 5, 6, 6, 7])

In [6]:
a = np.array([1,2,3,4,5,6,6,7.0])

In [7]:
a

array([1., 2., 3., 4., 5., 6., 6., 7.])

In [8]:
a = np.array([1,2,3,4,5,6,6.0,'7'])

In [9]:
a

array(['1', '2', '3', '4', '5', '6', '6.0', '7'], dtype='<U32')

In [10]:
a = np.array([[1,2,3,4],[5,6,6,7]])

In [11]:
a

array([[1, 2, 3, 4],
       [5, 6, 6, 7]])

In [13]:
a = np.array([1,2,3,4,5,6,6,7])
a.dtype
a.nbytes

32

In [15]:
import sys
a = list(range(1000))
sys.getsizeof(a)

8056

In [20]:
b =  np.array(range(1000), dtype = 'int8')
sys.getsizeof(b)

1104

In [21]:
b.nbytes

1000

In [22]:
b.itemsize


1

In [24]:
b.dtype

dtype('int8')

In [25]:
a = np.array([[1,2,3,4],[5,6,6,7]])

In [26]:
a.itemsize

4

In [27]:
a.size

8

In [28]:
a.dtype

dtype('int32')

In [29]:
a.ndim

2

In [32]:
a = np.array([[[1,2,3], [5,6,6]], [[1,1,1], [2,2,2]]])

In [33]:
a

array([[[1, 2, 3],
        [5, 6, 6]],

       [[1, 1, 1],
        [2, 2, 2]]])

In [34]:
a = np.array([[1,2,3,4],[5,6,6,7]])

In [35]:
a

array([[1, 2, 3, 4],
       [5, 6, 6, 7]])

In [36]:
a[0][3]

4

In [38]:
a[1][3]

7

In [39]:
a[1,3]

7

In [2]:
list(range(1,5,2))

[1, 3]

In [3]:
list(range(1,5,0.2))

TypeError: 'float' object cannot be interpreted as an integer

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
print(np.array([1,2,3,4,5]))#array dont have comma

[1 2 3 4 5]


In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(3.3, 5)

array([3.3, 4.3])

In [8]:
np.arange(3.5, 15, 0.5)

array([ 3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,
        9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. ,
       14.5])

In [14]:
np.arange(3.5, 15, 0.5, dtype ='int8')

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25], dtype=int8)

In [18]:
np.linspace(1, 10)
np.linspace(start = 1, num = 10, stop = 10, endpoint= False)

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [19]:
np.linspace(1, 10,endpoint=True, retstep=True)

(array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
         1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
         2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
         3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
         4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
         5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
         6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
         7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
         8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
         9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ]),
 0.1836734693877551)

In [27]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [32]:
np.zeros((4,3), dtype= 'int8')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [33]:
np.ones(4)

array([1., 1., 1., 1.])

In [34]:
np.ones((4,3), dtype= 'int8')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [35]:
np.full((2,3), fill_value=8)

array([[8, 8, 8],
       [8, 8, 8]])

In [41]:
np.full((3,3), fill_value=[1,-2,3])

array([[ 1, -2,  3],
       [ 1, -2,  3],
       [ 1, -2,  3]])

In [45]:
np.eye(4, dtype='int8')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [46]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [48]:
np.eye(3,6, k = 3)

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [49]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
np.empty(4)

array([1., 1., 1., 1.])

In [51]:
np.empty((2,3))

array([[1., 0., 0.],
       [0., 1., 0.]])

In [56]:
np.empty([3,6])

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])