In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])

In [3]:
a[1]

2

In [5]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [10]:
print(a.shape)
print(a.size)
print(a.dtype)

(2, 5)
10
int32


In [78]:
a = np.arange(1,41)

In [79]:
b = a.reshape((5,8))

In [80]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])

In [21]:
b[::2, ::2]

array([[ 1,  3,  5,  7],
       [17, 19, 21, 23],
       [33, 35, 37, 39]])

In [82]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [83]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])

In [85]:
b[1] =100

In [86]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8, 100, 100, 100, 100, 100,
       100, 100, 100,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40])

In [87]:
b

array([[  1,   2,   3,   4,   5,   6,   7,   8],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [ 17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40]])

In [22]:
b = np.arange(1,41).reshape(5,8)

In [23]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])

In [26]:
b[np.array([0,3,4]),np.array([3,4,5])]

array([ 4, 29, 38])

In [116]:
a= np.arange(5)

In [117]:
a

array([0, 1, 2, 3, 4])

In [118]:
a[[True, False, False, True, True]]

array([0, 3, 4])

In [127]:
ab = np.arange(5)

In [122]:
ab

array([0, 1, 2, 3, 4])

In [124]:
ac = np.arange(6,11)

In [125]:
ac

array([ 6,  7,  8,  9, 10])

In [111]:
b= np.arange(5), np.arange(6,11)

In [112]:
b


(array([0, 1, 2, 3, 4]), array([ 6,  7,  8,  9, 10]))

In [105]:
b = np.arange(49).reshape(7,7)

In [106]:
b

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [107]:
b[::2, ::2]

array([[ 0,  2,  4,  6],
       [14, 16, 18, 20],
       [28, 30, 32, 34],
       [42, 44, 46, 48]])

# numpy day 4

In [21]:
import numpy as np

In [22]:
a= [[1,2,3,4,5],[6,7,8,9,0]]

In [23]:
a

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]]

In [24]:
for item in enumerate(a):
    print(item)

(0, [1, 2, 3, 4, 5])
(1, [6, 7, 8, 9, 0])


In [25]:
i, j = 1,2

In [26]:
i


1

In [27]:
j

2

In [28]:
a = [1,2,3,4,5,6,7,8]

In [29]:
for item in enumerate(a):
    print(item)

(0, 1)
(1, 2)
(2, 3)
(3, 4)
(4, 5)
(5, 6)
(6, 7)
(7, 8)


In [30]:
for k,v in enumerate(a):
    print(k,v)

0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8


In [31]:
b = np.arange(49).reshape(7,7)

In [32]:
b


array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [33]:
b = np.arange(20)


In [35]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
a= [1,2,3,4]

In [37]:
b=[5,6,7,8]

In [38]:
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [39]:
import datetime

In [49]:
start = datetime.datetime.now()
for item in range(5000):
    pass

stop = datetime.datetime.now()
print(stop - start)
    
start1 = datetime.datetime.now()
for item in range(500000):
    pass

stop1 = datetime.datetime.now()
print(stop1 - start1)
    

0:00:00
0:00:00.016021


In [50]:
a= np.arange(20)

In [51]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [52]:
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [53]:
a.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [55]:
a.reshape(5,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [59]:
a.flatten(order = 'F')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [60]:
a= np.arange(20).reshape(5,4)

In [61]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [63]:
a = np.arange(10)

In [64]:
b = np.arange(10,20)

In [65]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [68]:
np.concatenate((a,b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
a = np.arange(10).reshape(5,2)
b = np.arange(10,20).reshape(5,2)

In [70]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [71]:
b

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [72]:
np.concatenate((a,b), axis = None)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [73]:
np.concatenate((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [74]:
np.concatenate((a,b), axis = 0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [75]:
np.concatenate((a,b), axis = 1)

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13],
       [ 4,  5, 14, 15],
       [ 6,  7, 16, 17],
       [ 8,  9, 18, 19]])

In [84]:
b = np.arange(10,20)

In [85]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [86]:
b[b%2==0]

array([10, 12, 14, 16, 18])

In [87]:
np.where(b%2==0)

(array([0, 2, 4, 6, 8], dtype=int64),)

In [93]:
a=[1,2,3,4]
b=[5,6,7,8]

for item in zip(a,b):
    print(item)
    
for i,j in zip(a,b):
    print(i+j)

(1, 5)
(2, 6)
(3, 7)
(4, 8)
6
8
10
12
